//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from HuskyLang.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="HuskyLangParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface IHuskyLangVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by the <c>ToExpression</c>
	/// labeled alternative in <see cref="HuskyLangParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitToExpression([NotNull] HuskyLangParser.ToExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ToLogical</c>
	/// labeled alternative in <see cref="HuskyLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitToLogical([NotNull] HuskyLangParser.ToLogicalContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LogicalOp</c>
	/// labeled alternative in <see cref="HuskyLangParser.logical"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalOp([NotNull] HuskyLangParser.LogicalOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ToCompare</c>
	/// labeled alternative in <see cref="HuskyLangParser.logical"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitToCompare([NotNull] HuskyLangParser.ToCompareContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ToPlusOrMinus</c>
	/// labeled alternative in <see cref="HuskyLangParser.compare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitToPlusOrMinus([NotNull] HuskyLangParser.ToPlusOrMinusContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CompareOp</c>
	/// labeled alternative in <see cref="HuskyLangParser.compare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompareOp([NotNull] HuskyLangParser.CompareOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ToMultOrDiv</c>
	/// labeled alternative in <see cref="HuskyLangParser.plusOrMinus"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitToMultOrDiv([NotNull] HuskyLangParser.ToMultOrDivContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AddSubOp</c>
	/// labeled alternative in <see cref="HuskyLangParser.plusOrMinus"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddSubOp([NotNull] HuskyLangParser.AddSubOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ToUnary</c>
	/// labeled alternative in <see cref="HuskyLangParser.multOrDiv"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitToUnary([NotNull] HuskyLangParser.ToUnaryContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MultiDivOp</c>
	/// labeled alternative in <see cref="HuskyLangParser.multOrDiv"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiDivOp([NotNull] HuskyLangParser.MultiDivOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UnaryOp</c>
	/// labeled alternative in <see cref="HuskyLangParser.unary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryOp([NotNull] HuskyLangParser.UnaryOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ToPower</c>
	/// labeled alternative in <see cref="HuskyLangParser.unary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitToPower([NotNull] HuskyLangParser.ToPowerContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ToAtom</c>
	/// labeled alternative in <see cref="HuskyLangParser.powr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitToAtom([NotNull] HuskyLangParser.ToAtomContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Power</c>
	/// labeled alternative in <see cref="HuskyLangParser.powr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPower([NotNull] HuskyLangParser.PowerContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ToLiteral</c>
	/// labeled alternative in <see cref="HuskyLangParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitToLiteral([NotNull] HuskyLangParser.ToLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ToIdentifier</c>
	/// labeled alternative in <see cref="HuskyLangParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitToIdentifier([NotNull] HuskyLangParser.ToIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncCall</c>
	/// labeled alternative in <see cref="HuskyLangParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncCall([NotNull] HuskyLangParser.FuncCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Braces</c>
	/// labeled alternative in <see cref="HuskyLangParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBraces([NotNull] HuskyLangParser.BracesContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ArrayIndex</c>
	/// labeled alternative in <see cref="HuskyLangParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayIndex([NotNull] HuskyLangParser.ArrayIndexContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HuskyLangParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgList([NotNull] HuskyLangParser.ArgListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HuskyLangParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] HuskyLangParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ConstantPI</c>
	/// labeled alternative in <see cref="HuskyLangParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantPI([NotNull] HuskyLangParser.ConstantPIContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ConstantE</c>
	/// labeled alternative in <see cref="HuskyLangParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantE([NotNull] HuskyLangParser.ConstantEContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Double</c>
	/// labeled alternative in <see cref="HuskyLangParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDouble([NotNull] HuskyLangParser.DoubleContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Int</c>
	/// labeled alternative in <see cref="HuskyLangParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInt([NotNull] HuskyLangParser.IntContext context);
}
